### ISSUE TITLE
last updated from yaml frontmatter not picked up?

### ISSUE THREAD

**Issue by RMHogervorst** [buvis/mkdocs-zettelkasten#25]
hi there, 
If I read this right <https://buvis.github.io/mkdocs-zettelkasten/features/20211123213357/>
a markdown file with yaml frontmatter

```yaml
---
id: 13234210812
title: a very nice title
tags: [tag1, tag2]
last_update: 2023-01-01 13:40:20
---
```
%Y-%m-%d %H:%M:%S

should change the date in the top right corner to 2023-01-01

Everything seems to work except the date part. I see only todays date. I copy the files over so git date is not available. 

What am I doing wrong?
